build: add Powershell scripts for Zig toolchain on Windows and use single script for running Zig on CI

diff --git a/tools/download_zig b/tools/download_zig
--- a/tools/download_zig
+++ b/tools/download_zig
@@ -196,7 +196,7 @@ main() {
     IFS=$_old_ifs
 
     if [ -z "${_selected_mirror}" ]; then
-        echo "failed to download and verify Zig from ${MAX_MIRROR_TRIES} mirrors" >&2
+        echo "failed to download and verify Zig from ${_max_tries} mirrors" >&2
         exit 1
     fi
 
